### ISSUE TITLE
ae_loss question

### ISSUE THREAD

**Issue by moothes** [princeton-vl/CornerNet#51]
I check your ae_loss function in kp_utils.py and I find that the 200th line you have `dist = dist - 1 / (num + 1e-4)`.  This means you subtract 1/n from each distance? why? I think this term have no effect on calculating the gradients of loss.

**Comment by heilaw** [comment]
That's correct. This term has no effect on calculating the gradients. I just added it to make sure the AE loss is the same as the equation in the paper.

**Comment by moothes** [comment]
Thanks for your reply! This paper means the paper that proposed the AE loss or the latest version of your CornerNet paper?  In the CornerNet paper that I have, **push loss** is defined as:
![default](https://user-images.githubusercontent.com/17693547/48748771-f0051980-ecb2-11e8-8051-97810670727d.JPG)
I can't find the 1/n.

**Comment by heilaw** [comment]
I was referring to the CornerNet paper.

If we do not subtract 1/n in line 200th, the equation would become L_{push} + 1/(n-1) after the summation. It is because the diagonal elements of `dist` are 1s instead of 0s. We subtract `dist` by 1/n then the 1s in the diagonal would be cancelled out in the summation.

**Comment by moothes** [comment]
well, I get it. Thank you for your excellent work and detailed explanation!

**Comment by igo312** [comment]
@heilaw directly subtract seems  work on all element.
does it need using a diag matrix? like `dist = dist - (1 / (num + 1e-4))* torch.eye(dist.shape[1])`?
